WebClientBattleShip/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using WebClientBattleShip.GameService;
using WebClientBattleShip.Models;
using WebClientBattleShip.Models.DtoModels;

namespace WebClientBattleShip.Controllers
{
    public class GameController : Controller
    {
        #region Main Views
        public ActionResult Index()
        {
            var userid = this.WorkWithCookie();
            var client = SingletonModel.GetInstance().Clients[userid];
            ViewBag.NameUser = client.Name;
            if (client.IsAuthorised)
            {
                client.ServiceClient.GetListAvailableGames();
                ViewBag.IsLogined = true;
                return View();
            }
            return new RedirectResult("~/Home/Index");
        }

        [HttpGet]
        public ActionResult GamesAvailable()
        {

            var userid = this.WorkWithCookie();
            var client = SingletonModel.GetInstance().Clients[userid];
            ViewBag.NameUser = client.Name;
            ViewBag.UserId = client.ClientId;
            if (client.IsAuthorised)
            {
                var availableGamesResponses = client.Callbacks.GetResponses(typeof (GetListGamesResponse));
                if (availableGamesResponses.Count > 0)
                {
                    var availableGamesResponse = availableGamesResponses.Last() as GetListGamesResponse;
                    availableGamesResponses.Remove(availableGamesResponse);
                    client.Callbacks.ClearResponses(availableGamesResponses);
                    if (availableGamesResponse.IsSuccess)
                    {
                        return View(availableGamesResponse.Games);
                    }
                    ViewBag.Error = availableGamesResponse.Error;
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult Statistics(string id = "")
        {
            var userid = this.WorkWithCookie();
            var client = SingletonModel.GetInstance().Clients[userid];
            ViewBag.NameUser = client.Name;
            if (client.IsAuthorised)
            {
                ViewBag.IsLogined = true;
                return View();
            }
            ViewBag.IsLogined = false;
            return new RedirectResult("~/Home/Index");
        }

        public ActionResult Game()
        {
            return View();
        }
        #endregion
        #region Partial Views
                public ActionResult TopPlayers()
                {
                    var userid = this.WorkWithCookie();
                    var client = SingletonModel.GetInstance().Clients[userid];
                    ViewBag.NameUser = client.Name;
                    if (client.IsAuthorised)
                    {
                        client.ServiceClient.GetTopPlayers();
                        var topPlayersResponses = client.Callbacks.GetResponses(typeof (GetTopPlayersResponse));
                        if (topPlayersResponses.Count > 0)
                        {
                            client.Callbacks.ClearResponses(topPlayersResponses);
                            var topPlayersResponse = topPlayersResponses.Last() as GetTopPlayersResponse;
                            if (topPlayersResponse.IsSuccess)
                            {
                                return View(topPlayersResponse.TopPlayers);
                            }
                            ViewBag.Error = topPlayersResponse.Error;
                        }
                    }
                    return View();
                }

                public ActionResult LastGames()
                {
                    var userid = this.WorkWithCookie();
                    var client = SingletonModel.GetInstance().Clients[userid];
                    ViewBag.NameUser = client.Name;
                    if (client.IsAuthorised)
                    {
                        client.ServiceClient.GetLastGames();
                        var lastGamesResponses = client.Callbacks.GetResponses(typeof (GetLastGamesResponse));
                        if (lastGamesResponses.Count > 0)
                        {
                            client.Callbacks.ClearResponses(lastGamesResponses);
                            var lastGameResponse = lastGamesResponses.Last() as GetLastGamesResponse;
                            if (lastGameResponse.IsSuccess)
                            {
                                return View(lastGameResponse.Games);
                            }
                            ViewBag.Error = lastGameResponse.Error;
                        }
                    }

                    return View();
                }


      
                public ActionResult BattleMap(bool enemy = false)
                {
                    return enemy?View(): View(TempData["Ships"]);
                }
        #endregion
        #region Actions
        [HttpGet]
        public ActionResult Play(string gameId)
        {
            var userid = this.WorkWithCookie();
            var client = SingletonModel.GetInstance().Clients[userid];
            ViewBag.NameUser = client.Name;
            if (client.IsAuthorised)
            {
                Guid gameGuid;
                if (Guid.TryParse(gameId, out gameGuid))
                {
                    var request = new ConnectToGameRequest() {GameId = gameGuid };
                    client.ServiceClient.ConnectToGame(request);
                    return new EmptyResult();
                }
                return new HttpStatusCodeResult(400);
            }
            return new RedirectResult("~/Home/Index");
        }

        [HttpGet]
        public ActionResult CreateGame()
        {
            var userid = this.WorkWithCookie();
            var client = SingletonModel.GetInstance().Clients[userid];
            ViewBag.NameUser = client.Name;
            if (client.IsAuthorised)
            {
                var request = new CreateGameRequest();
                client.ServiceClient.CreateGame(request);
                return new EmptyResult();
            }
            return new RedirectResult("~/Home/Index");
        }

        public bool AbortGame()
        {
            var userid = this.WorkWithCookie();
            var client = SingletonModel.GetInstance().Clients[userid];
            if (client.IsAuthorised)
            {
                var abortResponses = client.Callbacks.GetResponses(typeof (AbortGameResponse));
                if (abortResponses.Count > 0)
                {
                    client.Callbacks.ClearResponses(abortResponses);
                    return true;
                }
            }
            return false;
        }
        public ActionResult CheckOpponent()
        {
            var userid = this.WorkWithCookie();
            var client = SingletonModel.GetInstance().Clients[userid];
            ViewBag.NameUser = client.Name;
            if (!client.IsAuthorised)
            {
                return new RedirectResult("~/Home/Index");
            }
            var currentGameResponses = client.Callbacks.GetResponses(typeof(CurentGameResponse));
            if (currentGameResponses.Count > 0)
            {
                var currentGameResponse = currentGameResponses.Last() as CurentGameResponse;
                client.Callbacks.ClearResponses(currentGameResponses);
                if (currentGameResponse.IsSuccess)
                {
                    return View("ShipPlacement");
                }
            }
            return new EmptyResult();
        }

        [HttpGet]
        public ActionResult LeaveGame()
        {
            var userid = this.WorkWithCookie();
            var client = SingletonModel.GetInstance().Clients[userid];
            ViewBag.NameUser = client.Name;
            if (client.IsAuthorised)
            {
                client.ServiceClient.LeaveGame();
                return new EmptyResult();
            }
            return new RedirectResult("~/Home/Index");
        }

        [HttpPost]
        public string StartGame(Ships[] id)
        {
            var userid = this.WorkWithCookie();
            var client = SingletonModel.GetInstance().Clients[userid];
            if (id != null)
            {
                var shipsmassive = new DTOShip[10];
                for (var i = 0; i < id.Length; i++)
                {
                    shipsmassive[i] = new DTOShip()
                    {
                        Coordinates = new XYCoordinate() { X = id[i].x, Y = id[i].y },
                        DeckCount = id[i].length,
                        Orientation = id[i].position == "h" ? ShipOrientation.Horisontal : ShipOrientation.Vertical
                    };
                }
                TempData["Ships"] = id;
                var request = new SendReadyRequest() { Ships = shipsmassive };
                client.ServiceClient.SendReady(request);
                return "ships is sended";
            }
            var sendReadyResponses = client.Callbacks.GetResponses(typeof(SendReadyResponse));
            if (sendReadyResponses.Count > 0)
            {
                client.Callbacks.ClearResponses(sendReadyResponses);
                var sendReadyResponse = (sendReadyResponses.Last() as SendReadyResponse);
                if (sendReadyResponse.IsSuccess)
                {
                    return "ships is accepted";
                }
                return "ships are not accepted";
            }
            var opponentReadyResponses = client.Callbacks.GetResponses(typeof(SendOpponentIsReadyResponse));


WebClientBattleShip/Views/Game/BattleMap.cshtml
@model WebClientBattleShip.Models.DtoModels.Ships[]

@{
    Layout = null;
    ViewBag.Alphabet = "АБВГДЕЖЗИК";
}
<table class="battlefield-table">
    <tbody>
    @for (var i = 0; i < 10; i++)
    {
        <tr class="battlefield-row">
            @for (int j = 0; j < 10; j++)
            {
                <td class="battlefield-cell battlefield-cell__empty">
                    <div class="battlefield-cell-content" data-y="@i" data-x="@j" ondrop="drop(event)" ondragover="allowDrop(event)">
                        <span class="z"></span>
                        @if (i == 0)
                        {
                            <div class="marker marker__col">@ViewBag.Alphabet[@j]</div>

                        }
                        @if (j == 0)
                        {
                            <div class="marker marker__row">@(@i + 1)</div>
                        }
                        @if (@Model != null)
                        {
                            foreach (var mod in @Model)
                            {

                                if (mod.y == i && mod.x == j)
                                {
                                    <div class="ship-box ship-box__h @(mod.position=="v"?"vertical":"") @("ship" + mod.length)"></div>

                                }
                            }
                        }

                    </div>
                </td>
            }
        </tr>
    }
    </tbody>
</table>

WebClientBattleShip/Views/Game/Chat.cshtml
@model ICollection<WebClientBattleShip.Models.ChatMessage>
@{
    Layout = null;
}

<script type="text/javascript">
    function sendMessage() {
        var message = $("#usermsg").val().replace(/\s+/g, "+");
        $("#usermsg").val("");
        $("#chat").load("@Url.Action("UpdateChat", "Game")" + "?message=" + message);
        $("#chat").scrollTop(100000);
    }
</script>
            <table class="table">
                <tbody>
                @if (@Model != null)
                {
                    foreach (var message in @Model)
                    {
                        <tr>
                            <td>
                                @message.Date.ToShortTimeString()
                                <b>@message.UserName:</b>
                                @message.Message
                            </td>
                        </tr>

                    }
                }
                </tbody>
            </table>


WebClientBattleShip/Views/Game/Game.cshtml
@model WebClientBattleShip.Models.DtoModels.Ships[]
@{
    ViewBag.Title = "Игра";
}

<script type="text/javascript">

    var intervalAbortGame = setInterval(function() {
        $.post("/Game/AbortGame", function(data) {
            if (data == "True") {
                $("#chatRow").css("display", "none");
                clearInterval(interval);
                clearInterval(chatInterval);
                clearInterval(intervalAbortGame);
                $(".battlefield__rival").addClass('battlefield__wait');
                $("#myStep").css('display', 'none');
                $("#enemyStep").css('display', 'none');
                $("#winner").css("display", "block");
                $("#winner").text("Противник покинул игру! Найдите другого партнера!");
            }
        });
    },5000);

    function firstStep() {
        $.ajax({
            type: 'POST',
            url: '/Game/StartGame',
            success: function(response) {
                if (response.indexOf('your') + 1) {
                    $("#myStep").css('display', 'block');
                    $(".battlefield__rival").removeClass('battlefield__wait');
                } else {
                    $("#enemyStep").css('display', 'block');
                }
            }
        });
    };

    firstStep();
    var chatInterval = setInterval(function() {
        $("#chat").load("@Url.Action("UpdateChat", "Game")");
    }, 5000);
    var x;
    var y;
    $(document).ready(function() {
        $(".battlefield-cell-content").click(function() {
            x = $(this).data("x");
            y = $(this).data("y");
            $.get("/Game/Shot?x=" + x + "&y=" + y, function() {
            });
        });
    });

    var interval = setInterval(function() {

        $.ajax({
            type: 'GET',
            url: '/Game/Shot',
            dataType: 'json',
            contentType: 'application/json',
            success: function(response) {
                if (response !== "") {
                    var div;
                    if (response['IsYourStep']) {
                        div = $("#enemyMap .battlefield-cell-content[data-y=" + response['Y'] + "][data-x=" + response['X'] + "]");

                    } else {
                        div = $("#myMap .battlefield-cell-content[data-y=" + response['Y'] + "][data-x=" + response['X'] + "]");
                    }
                    if (response['IsMissed']) {
                        div.parent().removeClass('battlefield-cell__empty');
                        div.parent().addClass('battlefield-cell__miss');
                    } else {
                        div.parent().removeClass('battlefield-cell__empty');
                        div.parent().addClass('battlefield-cell__hit');
                        if (response['IsKilled']) {
                            var ship = response['Ship'];
                            for (var i = 0; i < ship['length']; i++) {
                                if (response['IsYourStep']) {
                                    if (ship["position"] === "h") {
                                        $("#enemyMap .battlefield-cell-content[data-y=" + ship['y'] + "][data-x=" + (ship['x'] + i) + "]").parent().addClass("battlefield-cell__done");
                                    } else {
                                        $("#enemyMap .battlefield-cell-content[data-y=" + (ship['y'] + i) + "][data-x=" + ship['x'] + "]").parent().addClass("battlefield-cell__done");
                                    }
                                }
                            }
                        }
                    }
                    if (response['IsYourNext']) {
                        $(".battlefield__rival").removeClass('battlefield__wait');
                        $("#myStep").css('display', 'block');
                        $("#enemyStep").css('display', 'none');
                    } else {
                        $(".battlefield__rival").addClass('battlefield__wait');
                        $("#myStep").css('display', 'none');
                        $("#enemyStep").css('display', 'block');
                    }
                    if (response['Winner']) {
                        $("#myStep").css('display', 'none');
                        $("#enemyStep").css('display', 'none');
                        $("#winner").css('display', 'block');
                        $("#chatRow").css('display', 'none');
                        $("#leaveGame").css('display', 'none');
                        $("#playAgain").css('display', 'block');
                        $("#winner").text("Игра закончена! Победил " + response["WinnerName"]);
                        $(".battlefield__rival").addClass('battlefield__wait');
                        clearInterval(interval);
                        clearInterval(chatInterval);
                    }
                }
            }
        });

    }, 600);
</script>
<div class="row">
    <div class="col-md-3 col-md-offset-2">

        <div class="alert alert-success text-center" style="display: none" id="myStep">Ваш ход!</div>
        <div class="alert alert-danger text-center" style="display: none;" id="enemyStep">Ход противника!</div>
        <div class="alert alert-success text-center" style="display: none" id="winner">
        </div>
    </div>
    <div class="col-md-3">
        <button type="button" onclick="location.href = '/Game/Index'" class="btn btn-success btn-block" id="playAgain" style="display: none">Сыграть еще!</button>

        <button type="button" onclick="location.href = '/Game/Index'" class="btn btn-danger btn-block" id="leaveGame">Покинуть игру!</button>
    </div>
</div>

    <div class="battlefield clearfix">
        <div class="battlefield battlefield__self">
            <div class="battlefield-gap">
                <div class="battlefield-table-placeholder">
                    <div class="" id="myMap">
                        @Html.Action("BattleMap");
                    </div>
                    <div class="battlefield-label">Ваше поле</div>

                </div>
            </div>
        </div>
        <div class="battlefield battlefield__rival battlefield__wait">
            <div class="battlefield-gap">
                <div class="battlefield-table-placeholder">
                    <div class="" id="enemyMap">
                        @Html.Action("BattleMap", new {enemy = true})
                    </div>
                    <div class="battlefield-label">Поле противника</div>

                </div>

            </div>
        </div>
    </div>

    <div class="row" id="chatRow">
        <div class="col-md-8 col-md-offset-2">
            <div name="chat" action="" class="panel panel-default">
                <div class="panel-heading panel-title">Чат с противником:</div>
                <div id="chat" style="height: 100px; overflow-y: auto">
                    @Html.Action("UpdateChat", "Game")
                </div>
                <div class="row">
                    <div class="col-md-7">
                        <input name="usermsg" placeholder="Введите сообщение..." type="text" id="usermsg" style="height: 33px; width: 100%;">
                    </div>
                    <div class="col-md-5">
                        <button type="submit" class="btn btn-success btn-block btn-bottom" onclick="sendMessage()">Отправить</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

WebClientBattleShip/Views/Game/GamesAvailable.cshtml
@model WebClientBattleShip.GameService.DTOAwaitingGame[]
@{
    Layout = null;
}
<script type="text/jscript">
    
    function connectToGame()
    {
        $.get('@Url.Action("Play", "Game")?gameId=' + $(':radio').filter(':checked').attr('id'));
        var timerCheckOpponent = setInterval(function () {
            $.get('@Url.Action("CheckOpponent", "Game")', function (data) {
                if(data!="")
                {
                    $("#content").html(data);
                    clearInterval(timerCheckOpponent);
                    clearInterval(timerId);
                }
            });
        }, 5000)

    }
</script>

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>@ViewBag.Error</div>

}
else
{
    <table class="table table-hover table-bordered" id="tab">
        <caption>
            <h3>Игры, к которым можно присоединиться</h3>
        </caption>
        <thead>
            <tr>
                <th>Игрок</th>
                <th class="right-col">Дата создания игры</th>
            </tr>
        </thead>
        <tbody>
            @if (@Model != null)
            {
                foreach (var x in @Model)
                {
                    <tr>
                        <td>@x.Creator.Login</td>
                        <td class="right-col">@x.CreationTime</td>
                        <td>
                            @if (ViewBag.UserId != x.Creator.Id)
                            {
                                <input type="radio" name="games" id="@x.GameId" />
                            }
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
}

WebClientBattleShip/Views/Game/Index.cshtml

@{
    ViewBag.Title = "Создание игры";
}

<script type="text/javascript">
    
    var timerId;

    setInterval(function () { $("#tableGames").load('@Url.Action("GamesAvailable", "Game")'); }, 5000);

    function createGame()
    {
        $.get('@Url.Action("CreateGame", "Game")');
        clearInterval(timerId);
        $('#timer').text("Вы ожидаете 0 секунд");
        var i = 1;
        timerId = setInterval(function () { $('#timer').text("Вы ожидаете " + i++ + " секунд..."); }, 1000);
        var timerCheckOpponent = setInterval(function () {
            $.get('@Url.Action("CheckOpponent", "Game")', function (data) {
                if (data !== "") {
                    $("#content").html(data);
                    clearInterval(timerCheckOpponent);
                    clearInterval(timerId);
                }
            });
        }, 2000);
        document.getElementById("leave").style.display = "block";
        document.getElementById("forShow").style.display = "block";
        document.getElementById("createGame").style.display = "none";


    }
    function leaveGame() {
        $.get('@Url.Action("LeaveGame", "Game")');
        document.getElementById("forShow").style.display = "none";
        document.getElementById("leave").style.display = "none";
        document.getElementById("createGame").style.display = "block";
    };
    window.onbeforeunload = function () {
        $.get("/Game/LeaveGame/");
    };
</script>

<div role="form">
    <div class="row">
        <div class="col-md-4 col-md-offset-3 alert alert-success" id="forShow" style="display: none">Вы находитесь в очереди игр! Ожидайте противника... <span id="timer"></span></div>
        <div class="col-md-4 col-md-offset-3 alert alert-danger" id="connectError" style="display: none">Ошибка при подключении к игре</div>

        <div class="col-md-2 col-md-offset-8" id="createGame">
            <button type="button" class="btn btn-primary btn-block" onclick="createGame()">Создать новую игру</button>
        </div>
        <div class="col-md-2 col-md-offset-1" id="leave" style="display:none">
            <button type="button" onclick="leaveGame()" class="btn btn-danger btn-block">Выйти</button>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3"> </div>
        <div class="col-md-6" id="tableGames">
            @Html.Action("GamesAvailable", "Game")
        </div>
        <div class="col-md-3"> </div>
    </div>
    <div class="row">
        <div class="col-md-3 col-md-offset-7">
            <button type="submit" class="btn btn-success btn-block" onclick=connectToGame()>Присоединиться к игре</button>
        </div>
        <div class="col-md-2"> </div>
    </div>
</div>
<div></div>

WebClientBattleShip/Views/Game/LastGames.cshtml
@model WebClientBattleShip.GameService.DTOFullGameInfo[]
@{
    Layout = null;
}

        @if (@ViewBag.Error != null)
        {
            <div class="alert alert-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>@ViewBag.Error</div>
        }
        else
        {
            <table class="table table-hover table-bordered" id="lastGames">
                <thead>
                <tr>
                    <th>Победитель</th>
                    <th>Проигравший</th>
                    <th>Дата</th>
                    <th>Длительность игры (мин.)</th>
                </tr>
                </thead>
                <tbody>
                @if (@Model != null)
                {
                    foreach (var games in @Model)
                    {
                        <tr>
                            <td>@games.Winner</td>
                            <td>@(@games.NamePlayer2 == @games.Winner? @games.NamePlayer1: @games.NamePlayer2)</td>
                            <td>@games.StartGame</td>
                            <td>@games.LongTime</td>
                        </tr>
                    }
                }
                </tbody>
            </table>
        }

WebClientBattleShip/Views/Game/Statistics.cshtml
@{
    ViewBag.Title = "Статистика";
}

<script type="text/javascript">
        function update() {
            setInterval(function() {
                $("#tab1").load("@Url.Action("TopPlayers","Game")");
                $("#tab2").load("@Url.Action("LastGames", "Game")");
            }, 5000);
        }
        update();
</script>
<div role="form">
    <div class="row">
        <div class="col-md-3"> </div>
        <div class="col-md-6 container">
            <br>
            <div class="tabs">
                <ul class="nav nav-tabs" role="tablist" id="tabs">
                    <li class="active" role="presentation"><a href="#tab1" aria-controls="tab1" role="tab" data-toggle="tab">Рейтинг игроков</a></li>
                    <li><a href="#tab2" aria-controls="tab2" role="tab" data-toggle="tab">Последние 100 игр</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab1">
                            @Html.Action("TopPlayers", "Game")
                    </div>
                    <div class="tab-pane" id="tab2">
                            @Html.Action("LastGames", "Game")
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebClientBattleShip/Views/Game/TopPlayers.cshtml
@model WebClientBattleShip.GameService.DTOFullUserInfo[]
@{
    Layout = null;
}
@if (@ViewBag.Error != null)
{
    <div class="alert alert-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>@ViewBag.Error</div>
}
else
{
    <table class="table table-hover table-bordered" id="topPlayers">
        <thead>
        <tr>
            <th>Место</th>
            <th>Игрок</th>
            <th>Сыграно игр</th>
            <th>Процент побед</th>
            <th>Дата регистрации</th>
        </tr>
        </thead>
        <tbody>
        @if (@Model != null)
        {
            var i = 1;
            foreach (var user in @Model)
            {
                <tr>
                    <td>@(i++)</td>
                    <td>@user.Login</td>
                    <td>@user.Games</td>
                    <td>@user.PercentWonGames</td>
                    <td>@user.DataRegister</td>
                </tr>
            }
        }
        </tbody>
    </table>
}